title: Isa Nazhmudinov
description: PHP/Python Developer (online-cv)
show_downloads: false
google_analytics: UA-144336853-1
github_profile: https://github.com/isagadji

theme_skin: ceramic
#theme_skin: blue
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
